### ISSUE TITLE
Can you help me make sense of this error?

### ISSUE THREAD

**Issue by tnilanon** [krisbuist/timeular-zei-linux#8]
Ubuntu 18.04 here. I can't find corresponding errors on syslog or kern.log

"Can't discover the profile: can't discover services: ATT request failed: input channel closed: io: read/write on closed pipe"

I get this error sometimes. The last occurrence was right after logging in.

Thanks for the good work.

**Comment by krisbuist** [comment]
The error originates from https://github.com/krisbuist/timeular-zei-linux/blob/95737b2a3f3a4b7578c2cec2f50c90c134816861/BluetoothManager.go#L55

and is an error generated by the Bluetooth library used in this application, specifically here: https://github.com/currantlabs/ble/blob/c1d21c164cf83d3360fd5abd73a3405cb588c06c/linux/gatt/client.go#L63

I am not sure how and why this error occurs. Are you maybe connecting multiple Bluetooth devices to your pc?
The error message indicates that the IO channel for the BT client was closed (unexpectedly). Unfortunately, I can't do anything else but to guess. Maybe the maintainers of https://github.com/currantlabs/ble (or an active fork of the lib) can give you more detailed insight

**Comment by tnilanon** [comment]
That particular PC only has one Bluetooth device connected to it. I guess I'll try to wrap a script around your program and make it into a systemd service that pauses and auto-restarts when crashed. (Edit: I want to try to resolve the error first though.)

From your guess, I believe my Bluetooth might not wake up smoothly after a long computer sleep. ~This particular crash usually happens at the first login of the day.~ ~Maybe the wake-up latency exceeds the IO channel delay threshold.~

Thank you!

**Comment by tnilanon** [comment]
The error shows up like this. I'll try my hand on this and see how it goes.

```
.
.
2019/03/08 16:21:23 ZEI disconnected
2019/03/08 16:21:23 Trying to connect to the ZEI
2019/03/08 16:21:23 Connected to the ZEI
2019/03/08 16:21:24 Device side: 9
2019/03/08 16:21:24 Subscribed to ZEI side changes
2019/03/08 19:20:30 ZEI disconnected
2019/03/08 19:20:30 Trying to connect to the ZEI
2019/03/08 19:20:30 Connected to the ZEI
2019/03/08 19:20:31 Device side: 9
2019/03/08 19:20:31 Subscribed to ZEI side changes
2019/03/08 22:17:15 ZEI disconnected
2019/03/08 22:17:15 Trying to connect to the ZEI
2019/03/08 22:17:15 Connected to the ZEI
2019/03/08 22:17:16 Device side: 9
2019/03/08 22:17:16 Subscribed to ZEI side changes
2019/03/09 01:15:00 ZEI disconnected
2019/03/09 01:15:00 Trying to connect to the ZEI
2019/03/09 01:15:00 Connected to the ZEI
2019/03/09 01:15:01 Device side: 9
2019/03/09 01:15:01 Subscribed to ZEI side changes
2019/03/09 04:12:40 ZEI disconnected
2019/03/09 04:12:40 Trying to connect to the ZEI
2019/03/09 04:12:40 Connected to the ZEI
2019/03/09 04:12:40 Can't discover the profile: can't discover services: ATT request failed: input channel closed: io: read/write on closed pipe
```

**Comment by tnilanon** [comment]
This error no longer occurs. I suspect the cause to be the Bluetooth firmware.

**Comment by krisbuist** [comment]
Thanks for the update. Good to hear :)
